spring:
  mail:
    host: smtp.163.com #SMTP
    username: hq_learn@163.com #发送方邮箱账号
    password: IFHUHCMBVJXBKVJN #授权码
    properties:
      from: hq_learn@163.com #
  thymeleaf:
    cache: false
    prefix: classpath:/views/
  servlet:
    multipart:
      max-file-size: 10MB #单文件大小限制
      max-request-size: 50MB #总文件大小限制
